# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyCommandsIOSExample' do
  use_frameworks!

  pod 'KeyCommands', :path => './../KeyCommands.podspec.json'
end

target 'KeyCommandsTvOSExample' do
  use_frameworks!

  pod 'KeyCommands', :path => './../KeyCommands.podspec.json'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
